# https://taskfile.dev/usage/
version: '3'
tasks:
  default: |
    task t
    task bio-check

  b: bun run build
  t: bun test ./test/**
  run: bun run src/index.ts
  i: bun i # bun install

  bio-check: |
    # bunx biome check --fix .
    bunx biome check
  
  dry-npm: bunx semantic-release --dry-run

  test-demo: |
    cd demo
    bun update 
    bun test
    
  # publish
  # https://bun.sh/docs/cli/publish
  pub: bun publish # --dry-run --auth-type web --access public
  login: npm login --auth-type web
  rel-local: bun run semantic-release --dry-run
  np: bun x np

  setup: |
    # ts support for bun api and node api
    bun add -d @types/bun
    bun add -d typescript
    # https://github.com/egoist/tsup
    bun add -d tsup

    bun add -d semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/npm

    bun add -d @commitlint/{cli,config-conventional}
    echo "export default { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
    # echo "for: bar" | bun x commitlint

    bun add -d husky
    # bunx husky init
    ## .husky/pre-commit
    # prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
    # git update-index --again
    # skip git hooks
    # git commit -m "..." -n # Skips Git hooks
    # HUSKY=0 git ... # Temporarily disables all Git hooks

    ## Add commit message linting to commit-msg hook
    # echo "bunx --no -- commitlint --edit \$1" > .husky/commit-msg
    ## test it
    # bunx commitlint --from HEAD~1 --to HEAD --verbose
    # bunx commitlint --last --verbose

    bun add --dev --exact @biomejs/biome
    bunx @biomejs/biome check --write ./src
    bunx biome init --jsonc
    # bunx biome format --write <files>
    # bunx biome lint --write <files>
    ## The check command runs multiple tools at once. It formats, lints, and organizes imports.
    # bunx biome check --write <files>

    # bun add -d eslint prettier eslint-config-prettier eslint-plugin-prettier
    # bun rm eslint prettier eslint-config-prettier eslint-plugin-prettier

  mk-hello: bun init